# Generated by Django 5.0.2 on 2024-03-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
