# Generated by Django 5.0.2 on 2024-03-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='brand',
        ),
    ]
