# Generated by Django 5.0.2 on 2024-03-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
